
"use client";
import {useState} from "react";
import Link from "next/link";
import {MusicShell} from "../../components/MusicShell";
import {BadgeCheck,Edit3,Heart,MoreHorizontal,Play,Share2,Users} from "lucide-react";
import s from "../../components/music.module.css";
const mixes=["Afterglow","Midnight Drive","Cloud Nine","Hyper Focus"];
export default function ProfilePage(){const[following,setFollowing]=useState(false);return <MusicShell><section className={s.socialHero}><div className={s.profileAvatar}>J</div><div><span>PUBLIC PROFILE</span><h1>Jade</h1><p>@jadepulse · Brisbane · listening since 2026</p><div className={s.socialStats}><b>48 playlists</b><b>2.4K followers</b><b>186 following</b></div><div className={s.socialActions}><button onClick={()=>setFollowing(!following)}>{following?"Following":"Follow"}</button><button><Edit3/> Edit profile</button><button><Share2/></button><button><MoreHorizontal/></button></div></div></section><section className={s.section}><div className={s.head}><div><span><Users/> SOCIAL</span><h2>Recently shared</h2></div></div><div className={s.cards}>{mixes.map((m,i)=><Link className={s.card} href={i===0?"/playlist/afterglow":"#"} key={m}><div className={[s.art,[s.purple,s.pink,s.blue,s.green][i]].join(" ")}><Play/></div><b>{m}</b><p>{i+12} collaborators · updated today</p></Link>)}</div></section><section className={s.profileGrid}><div className={s.feedPanel}><h2>Listening activity</h2>{["Liked Neon Hearts","Joined Midnight Drive room","Added City Lights to Afterglow","Followed Astra Vale"].map((x,i)=><div className={s.activityItem} key={x}><span>{["♥","◎","＋","✓"][i]}</span><div><b>{x}</b><small>{i+1}h ago</small></div></div>)}</div><div className={s.feedPanel}><h2>Top listeners</h2>{["Mila","Kairo","Lumi","Noah"].map((x,i)=><Link className={s.personRow} href="/profile/jade" key={x}><span>{x[0]}</span><div><b>{x}</b><small>{420-i*73} mutual minutes</small></div><BadgeCheck/></Link>)}</div></section></MusicShell>}
