"use client";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {FormEvent,useState} from "react";
import {ArrowLeft,AtSign,Check,Eye,EyeOff,KeyRound,Lock,Mail,ShieldCheck,Sparkles,User} from "lucide-react";
type Mode="login"|"signup"|"forgot-password"|"forgot-username";
type Account={name:string;username:string;email:string;password:string;role?:"owner"|"user"};
const OWNER_EMAIL="jade.luneft@gmail.com",USERS_KEY="bruhwiks_users",SESSION_KEY="bruhwiks_session";
export default function AuthExperience({mode}:{mode:Mode}){const router=useRouter();const[show,setShow]=useState(false);const[msg,setMsg]=useState("");const[err,setErr]=useState("");const copy={login:["Welcome back","Sign in to return to your sound universe.","Enter BruhWiks"],signup:["Create your identity","Build your profile and shape your own music world.","Create account"],"forgot-password":["Reset your password","Prepare a secure recovery link for your account.","Send reset link"],"forgot-username":["Find your username","Recover your BruhWiks identity.","Recover username"]}[mode];
const users=()=>{try{return JSON.parse(localStorage.getItem(USERS_KEY)||"[]")as Account[]}catch{return[]}};
function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setErr("");setMsg("");const d=new FormData(e.currentTarget),email=String(d.get("email")||"").trim().toLowerCase(),username=String(d.get("username")||"").trim(),name=String(d.get("name")||"").trim(),password=String(d.get("password")||""),list=users();if(mode==="signup"){if(!name||!username||!email||password.length<8)return setErr("Complete every field and use at least 8 password characters.");if(list.some(u=>u.email===email||u.username.toLowerCase()===username.toLowerCase()))return setErr("That email or username is already registered.");const role=email===OWNER_EMAIL?"owner":"user";localStorage.setItem(USERS_KEY,JSON.stringify([...list,{name,username,email,password,role}]));localStorage.setItem(SESSION_KEY,JSON.stringify({name,username,email,role}));router.push(role==="owner"?"/owner":"/");return}if(mode==="login"){const id=String(d.get("identity")||"").trim().toLowerCase(),a=list.find(u=>u.email===id||u.username.toLowerCase()===id);if(!a||a.password!==password)return setErr("Incorrect email, username, or password.");const role=a.email===OWNER_EMAIL?"owner":a.role||"user";localStorage.setItem(SESSION_KEY,JSON.stringify({name:a.name,username:a.username,email:a.email,role}));router.push(role==="owner"?"/owner":"/");return}const a=list.find(u=>u.email===email);if(!a)return setErr("No BruhWiks account was found with that email.");setMsg(mode==="forgot-username"?`Your username is ${a.username}.`:"Recovery instructions are ready for the production email system.")}
return <main className="auth-shell"><Link href="/" className="auth-back"><ArrowLeft/>Back to BruhWiks</Link><section className="auth-card"><div className="auth-brand"><span><Sparkles/></span><b>BruhWiks</b><small>Pulse</small></div><div className="auth-icon">{mode==="signup"?<User/>:mode==="forgot-username"?<AtSign/>:mode==="forgot-password"?<KeyRound/>:<ShieldCheck/>}</div><h1>{copy[0]}</h1><p>{copy[1]}</p><form onSubmit={submit} className="auth-form">{mode==="signup"&&<><label>Display name<div className="auth-input"><User/><input name="name"/></div></label><label>Username<div className="auth-input"><AtSign/><input name="username"/></div></label></>}{mode!=="login"&&<label>Email address<div className="auth-input"><Mail/><input name="email" type="email"/></div></label>}{mode==="login"&&<label>Email or username<div className="auth-input"><Mail/><input name="identity"/></div></label>}{(mode==="login"||mode==="signup")&&<label>Password<div className="auth-input"><Lock/><input name="password" type={show?"text":"password"}/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff/>:<Eye/>}</button></div></label>}{err&&<div className="auth-error">{err}</div>}{msg&&<div className="auth-success"><Check/>{msg}</div>}<button className="auth-submit">{copy[2]}</button></form>{mode==="login"&&<div className="auth-links"><Link href="/forgot-password">Forgot password?</Link><Link href="/forgot-username">Forgot username?</Link></div>}<div className="auth-switch">{mode==="signup"?<>Already have an account? <Link href="/login">Log in</Link></>:mode==="login"?<>New to BruhWiks? <Link href="/signup">Create account</Link></>:<>Remembered it? <Link href="/login">Return to login</Link></>}</div></section></main>}
