
"use client";
import Link from "next/link";
import {usePathname} from "next/navigation";
import {useState} from "react";
import {Home,Search,Library,Radio,Download,History,Heart,ListMusic,Play,Pause,SkipBack,SkipForward,Repeat2,Shuffle,Volume2,List,MonitorSpeaker,Sparkles,Bell,ChevronLeft,ChevronRight,Plus,Users,MessageCircle} from "lucide-react";
import s from "./music.module.css";
const links=[["/","Home",Home],["/search","Search",Search],["/library","Library",Library],["/live","Live",Radio],["/community","Community",Users],["/rooms","Rooms",MessageCircle],["/downloads","Downloads",Download],["/history","History",History]] as const;
export function MusicShell({children}:{children:React.ReactNode}){const p=usePathname();const[playing,setPlaying]=useState(true);const[liked,setLiked]=useState(false);return <main className={s.app}><aside className={s.sidebar}><Link href="/" className={s.brand}><span><Sparkles/></span><b>BruhWiks<small>music, reimagined</small></b></Link><nav>{links.map(([h,l,I])=><Link key={h} href={h} className={p===h?s.active:""}><I/>{l}</Link>)}</nav><label>YOUR SPACE</label><nav><Link href="/library"><Heart/>Favourites</Link><Link href="/playlist/afterglow"><ListMusic/>Afterglow</Link></nav><button className={s.create}><Plus/><span>Create a mix<small>Blend tracks and friends</small></span></button><Link href="/owner" className={s.profile}><span>J</span><b>Jade<small>Pulse member</small></b></Link></aside><section className={s.stage}><header className={s.top}><div><button><ChevronLeft/></button><button><ChevronRight/></button></div><Link href="/search" className={s.search}><Search/>Search the BruhWiks universe</Link><button><Bell/></button><Link href="/login" className={s.avatar}>J</Link></header><div className={s.content}>{children}</div></section><footer className={s.player}><div className={s.now}><span>NB</span><div><b>Neon Hearts</b><small>Astra Vale · Night Bloom</small></div><button onClick={()=>setLiked(!liked)} className={liked?s.liked:""}><Heart fill={liked?"currentColor":"none"}/></button></div><div className={s.transport}><div><button><Shuffle/></button><button><SkipBack/></button><button className={s.play} onClick={()=>setPlaying(!playing)}>{playing?<Pause fill="currentColor"/>:<Play fill="currentColor"/>}</button><button><SkipForward/></button><button><Repeat2/></button></div><section><small>1:18</small><i><b/></i><small>3:42</small></section></div><div className={s.tools}><List/><MonitorSpeaker/><Volume2/><i><b/></i></div></footer></main>}
