
"use client";
import Link from "next/link";
import {Play,ArrowRight,Users,TrendingUp,Clock3,Radio} from "lucide-react";
import {MusicShell} from "./components/MusicShell";
import s from "./components/music.module.css";
const recent=[["Night Bloom","Astra Vale","purple"],["Afterglow","Made for Jade","pink"],["Cloudline","Mila Rose","blue"],["Zero Gravity","Kairo","green"],["Soft Static","Northstar","orange"],["Heatwave","Juno Skye","violet"]];
const mixes=[["Midnight Drive","Synthwave, alt-pop and neon energy","purple"],["Main Character","Big hooks and confidence","pink"],["Velvet Hours","Late-night R&B in slow motion","violet"],["Hyper Focus","Electronic focus without distractions","green"],["Cloud Nine","Dream pop and soft electronic","blue"]];
export default function Home(){return <MusicShell><section className={s.hero}><div><span>BRUHWIKS ORIGINAL</span><h1>Your sound.<br/><em>Your universe.</em></h1><p>A living music feed shaped by your mood, your history and the people listening with you.</p><div className={s.heroButtons}><button><Play fill="currentColor"/>Start your mix</button><Link href="/search">Explore music <ArrowRight/></Link></div><div className={s.heroMeta}><b><Users/>4.2M listening now</b><b><TrendingUp/>98% taste match</b></div></div><div className={s.visual}><i/><div>AV<small>Night Bloom</small></div><b>LIVE<br/>12.8K</b></div></section><Section title="Continue listening" icon={<Clock3/>}><div className={s.quickGrid}>{recent.map(([t,a,c],i)=><Link href={i===0?"/album/night-bloom":"/playlist/afterglow"} className={s.quick} key={t}><span className={s[c]}/><div><b>{t}</b><small>{a}</small></div><button><Play fill="currentColor"/></button></Link>)}</div></Section><Section title="Made for Jade"><div className={s.cards}>{mixes.map(([t,d,c])=><Link href="/playlist/afterglow" className={s.card} key={t}><div className={s[c]}><strong>{t.slice(0,2)}</strong><button><Play fill="currentColor"/></button></div><b>{t}</b><p>{d}</p></Link>)}</div></Section><div className={s.columns}><section className={s.chart}><Head title="Trending now"/>{["Neon Hearts","Out of Orbit","Silverline","No Signal","Gravity"].map((x,i)=><div className={s.chartRow} key={x}><strong>0{i+1}</strong><span className={s[["purple","pink","blue","green","orange"][i]]}/><div><b>{x}</b><small>{["Astra Vale","Kairo","Mila Rose","Northstar","Juno Skye"][i]}</small></div><em>+{12+i*3}</em><Play/></div>)}</section><section className={s.live}><Radio/><span>LIVE ROOM</span><h2>Night Shift</h2><p>2,486 listeners sharing a late-night electronic set.</p><button>Join the room</button></section></div></MusicShell>}
function Head({title}:{title:string}){return <div className={s.head}><div><span>BRUHWIKS PULSE</span><h2>{title}</h2></div><Link href="/search">View all <ArrowRight/></Link></div>}
function Section({title,icon,children}:{title:string;icon?:React.ReactNode;children:React.ReactNode}){return <section className={s.section}><div className={s.head}><div><span>{icon} PERSONALIZED</span><h2>{title}</h2></div><Link href="/library">View all <ArrowRight/></Link></div>{children}</section>}
